services:
  mysql:
    image: mysql:latest
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_id
      MYSQL_PASSWORD: test_pw
      MYSQL_ROOT_PASSWORD: root_pw
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: